apiVersion: apps/v1
kind: Deployment
metadata:
  name: cex-frontend
  namespace: cex-exchange
  labels:
    app: cex-frontend
    component: frontend
    version: v1
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: cex-frontend
  template:
    metadata:
      labels:
        app: cex-frontend
        component: frontend
        version: v1
    spec:
      imagePullSecrets:
      - name: registry-credentials
      containers:
      - name: frontend
        image: ghcr.io/your-org/cex-exchange-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        env:
        # ConfigMap environment variables
        - name: REACT_APP_API_URL
          valueFrom:
            configMapKeyRef:
              name: cex-frontend-config
              key: REACT_APP_API_URL
        - name: REACT_APP_WS_URL
          valueFrom:
            configMapKeyRef:
              name: cex-frontend-config
              key: REACT_APP_WS_URL
        - name: REACT_APP_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: cex-frontend-config
              key: REACT_APP_ENVIRONMENT
        - name: REACT_APP_VERSION
          valueFrom:
            configMapKeyRef:
              name: cex-frontend-config
              key: REACT_APP_VERSION
        - name: REACT_APP_SENTRY_DSN
          valueFrom:
            configMapKeyRef:
              name: cex-frontend-config
              key: REACT_APP_SENTRY_DSN
        - name: REACT_APP_GOOGLE_ANALYTICS_ID
          valueFrom:
            configMapKeyRef:
              name: cex-frontend-config
              key: REACT_APP_GOOGLE_ANALYTICS_ID
        - name: REACT_APP_RECAPTCHA_SITE_KEY
          valueFrom:
            configMapKeyRef:
              name: cex-frontend-config
              key: REACT_APP_RECAPTCHA_SITE_KEY
        - name: REACT_APP_STRIPE_PUBLISHABLE_KEY
          valueFrom:
            configMapKeyRef:
              name: cex-frontend-config
              key: REACT_APP_STRIPE_PUBLISHABLE_KEY
        - name: REACT_APP_PAYPAL_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: cex-frontend-config
              key: REACT_APP_PAYPAL_CLIENT_ID
        - name: REACT_APP_SUPPORT_EMAIL
          valueFrom:
            configMapKeyRef:
              name: cex-frontend-config
              key: REACT_APP_SUPPORT_EMAIL
        - name: REACT_APP_COMPANY_NAME
          valueFrom:
            configMapKeyRef:
              name: cex-frontend-config
              key: REACT_APP_COMPANY_NAME
        - name: REACT_APP_TERMS_URL
          valueFrom:
            configMapKeyRef:
              name: cex-frontend-config
              key: REACT_APP_TERMS_URL
        - name: REACT_APP_PRIVACY_URL
          valueFrom:
            configMapKeyRef:
              name: cex-frontend-config
              key: REACT_APP_PRIVACY_URL
        
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        
        startupProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
        
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
        - name: nginx-cache
          mountPath: /var/cache/nginx
        - name: nginx-run
          mountPath: /var/run
        
        securityContext:
          runAsNonRoot: true
          runAsUser: 101
          runAsGroup: 101
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
      
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
          items:
          - key: nginx.conf
            path: nginx.conf
      - name: nginx-cache
        emptyDir: {}
      - name: nginx-run
        emptyDir: {}
      
      securityContext:
        fsGroup: 101
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - cex-frontend
              topologyKey: kubernetes.io/hostname
      
      tolerations:
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 300
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 300
---
apiVersion: v1
kind: Service
metadata:
  name: cex-frontend
  namespace: cex-exchange
  labels:
    app: cex-frontend
    component: frontend
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: cex-frontend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cex-frontend-pdb
  namespace: cex-exchange
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: cex-frontend
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cex-frontend-hpa
  namespace: cex-exchange
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cex-frontend
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 1
        periodSeconds: 60
      selectPolicy: Max